[package]
name = "mev-backrunning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "1.0.0", features = ["rustls"] }
tokio = { version = "1.23.0", features = ["macros"] }
